export type Location = {
  slug: string; name: string; eyebrow: string; title: string; description: string; headline: string; intro: string;
  contextTitle: string; context: string; focus: string[]; approachTitle: string; approach: { title: string; text: string }[]; links: string[];
};

export const locations: Location[] = [
  {
    slug: "dortmund", name: "Dortmund", eyebrow: "Webdesign für Dortmund", title: "Webdesign Dortmund: Websites, SEO & Software", description: "Individuelles Webdesign, SEO, GEO, AEO und Software für Unternehmen in Dortmund. Klare Strategie, schnelle Technik und mehr qualifizierte Anfragen.", headline: "Digitale Substanz für Dortmunds Unternehmen.",
    intro: "Dortmund verbindet Industriegeschichte, Technologie und einen starken Mittelstand. Genau diese Mischung braucht Websites, die Kompetenz nicht nur behaupten, sondern verständlich belegen und Interessenten sicher zur Anfrage führen.",
    contextTitle: "Sichtbar im Wettbewerb zwischen Ruhrgebiet und digitalem Markt", context: "Ob Dienstleister rund um den Wall, Handwerksbetrieb in Aplerbeck oder Technologieunternehmen am Phoenix-See: Die Suche beginnt oft lokal, die Auswahl findet digital statt. Wir entwickeln Seiten, die beides zusammenbringen – lokale Relevanz für Suchanfragen aus Dortmund und eine professionelle Darstellung, die auch überregional trägt.",
    focus: ["Lokale Landingpages für Dortmunder Suchanfragen", "Technische SEO für messbare Sichtbarkeit", "B2B-Websites mit klaren Leistungswegen", "Funnel für Beratung, Angebot oder Termin"],
    approachTitle: "Was für Dortmunder Projekte häufig zählt", approach: [{ title: "Kompetenz schnell erfassbar", text: "Komplexe Leistungen werden so strukturiert, dass Entscheider in kurzer Zeit Nutzen, Ablauf und nächsten Schritt verstehen." }, { title: "Lokal, ohne kleinteilig zu wirken", text: "Stadtbezug und regionale Signale ergänzen die Marke, ohne die Website auf Dortmund zu begrenzen." }, { title: "Saubere Übergabe", text: "Sie erhalten Projektdateien und Dokumentation – oder buchen Deployment, Domain und laufende Betreuung direkt hinzu." }], links: ["bochum", "witten", "castrop-rauxel", "nrw"]
  },
  {
    slug: "castrop-rauxel", name: "Castrop-Rauxel", eyebrow: "Webdesign für Castrop-Rauxel", title: "Webdesign Castrop-Rauxel für lokale Unternehmen", description: "Websites und digitale Lösungen für Unternehmen in Castrop-Rauxel: individuell, suchmaschinenfreundlich und auf echte Anfragen ausgerichtet.", headline: "Eine starke Website für den Standort zwischen den Zentren.",
    intro: "Castrop-Rauxel liegt mitten im Ruhrgebiet – und damit in einem Markt, in dem Kundinnen und Kunden mehrere Städte gleichzeitig vergleichen. Eine lokale Website muss deshalb Nähe zeigen und zugleich professionell genug für den gesamten regionalen Wettbewerb sein.",
    contextTitle: "Nicht zwischen Dortmund und Recklinghausen verschwinden", context: "Viele Betriebe werden weiterempfohlen, verlieren aber digitale Anfragen an besser aufgestellte Wettbewerber aus den Nachbarstädten. Wir übersetzen persönliche Verlässlichkeit in eine klare Website: mit nachvollziehbaren Leistungen, regionalen Suchsignalen und einem Kontaktweg, der auf Mobilgeräten genauso gut funktioniert wie am Desktop.",
    focus: ["Websites für inhabergeführte Betriebe", "Lokale SEO-Struktur ohne Textkopien", "Modernisierung bestehender Auftritte", "Einfache Anfrage- und Rückrufprozesse"],
    approachTitle: "Pragmatisch geplant, individuell gebaut", approach: [{ title: "Bestehendes sinnvoll nutzen", text: "Gute Inhalte, Domains und vorhandene Sichtbarkeit bleiben erhalten. Ersetzt wird nur, was das Ergebnis bremst." }, { title: "Regionale Reichweite", text: "Interne Verlinkung und Inhalte verbinden Castrop-Rauxel sinnvoll mit relevanten Nachbarstädten." }, { title: "Pflege ohne Abhängigkeit", text: "Klare Dokumentation und übergebbare Projektdateien sorgen dafür, dass Sie handlungsfähig bleiben." }], links: ["dortmund", "herne", "recklinghausen", "nrw"]
  },
  {
    slug: "herne", name: "Herne", eyebrow: "Webdesign für Herne", title: "Webdesign Herne: sichtbar, schnell, verständlich", description: "Professionelle Websites, lokale SEO und digitale Prozesse für Unternehmen in Herne. Individuelle Umsetzung statt austauschbarer Agenturvorlage.", headline: "In Herne gefunden. Digital überzeugt.",
    intro: "Wer in Herne nach einem Anbieter sucht, entscheidet oft in wenigen Augenblicken, welche Website Vertrauen schafft. Dafür braucht es keine lauten Versprechen, sondern klare Leistungen, belastbare Informationen und eine technisch einwandfreie Nutzung.",
    contextTitle: "Lokale Nachfrage in klare digitale Wege übersetzen", context: "Herne ist kompakt, aber der digitale Wettbewerb reicht weit darüber hinaus. Unsere Websites beantworten die Fragen, die vor einer Kontaktaufnahme wirklich entstehen: Passt die Leistung? Ist der Anbieter erreichbar? Wie läuft die Zusammenarbeit? Was kostet der Einstieg? Diese Klarheit unterstützt sowohl klassische Suche als auch KI-basierte Antworten.",
    focus: ["Mobile Nutzerführung für lokale Suchen", "AEO-Inhalte für konkrete Kundenfragen", "Performance-Optimierung älterer Websites", "Kontaktstrecken mit wenig Reibung"],
    approachTitle: "Für kurze Wege und klare Entscheidungen", approach: [{ title: "Mobile zuerst gedacht", text: "Lokale Suchen passieren häufig unterwegs. Inhalte, Navigation und Anfrage bleiben auf kleinen Displays konsequent nutzbar." }, { title: "Antworten statt Fülltext", text: "Preise, Leistungen und Abläufe werden dort erklärt, wo Unsicherheit sonst zum Absprung führt." }, { title: "Technik im Hintergrund", text: "SSL, DNS, SMTP und Deployment werden auf Wunsch vollständig eingerichtet und geprüft." }], links: ["bochum", "castrop-rauxel", "recklinghausen", "nrw"]
  },
  {
    slug: "bochum", name: "Bochum", eyebrow: "Webdesign für Bochum", title: "Webdesign Bochum für Wachstum und Sichtbarkeit", description: "Individuelle Websites, SEO, CRO und Software für Bochumer Unternehmen – von der klaren Landingpage bis zum digitalen Kundensystem.", headline: "Websites für Bochum, die aus Interesse Handlung machen.",
    intro: "Bochum steht für Wissen, Kultur, Gesundheitswirtschaft und einen Mittelstand im Wandel. Gute digitale Auftritte müssen dieser Vielfalt gerecht werden: präzise in der Ansprache, schnell in der Nutzung und offen für Wachstum.",
    contextTitle: "Von der Uni-Stadt bis zum regionalen B2B-Markt", context: "Zwischen Innenstadt, Technologiequartier und den gewachsenen Stadtteilen unterscheiden sich Zielgruppen und Suchanlässe deutlich. Wir planen deshalb nicht von einer Designvorlage aus, sondern von der Entscheidungssituation Ihrer Kundschaft. Daraus entstehen Seiten, Landingpages und digitale Werkzeuge, die eine konkrete Aufgabe erfüllen.",
    focus: ["Conversion-orientierte Unternehmenswebsites", "SEO und GEO für erklärungsbedürftige Angebote", "Landingpages für Kampagnen", "Webapps und interne Werkzeuge"],
    approachTitle: "Strategie, Gestaltung und Entwicklung aus einer Hand", approach: [{ title: "Suchintention verstehen", text: "Inhalte orientieren sich daran, welche Antwort Menschen in Bochum tatsächlich suchen – nicht an bloßer Keyword-Wiederholung." }, { title: "Conversion messbar vorbereiten", text: "Kontaktpunkte, Landingpages und Tracking-Struktur werden so angelegt, dass spätere Optimierung möglich ist." }, { title: "Systeme verbinden", text: "Wenn Formulare nicht reichen, entwickeln wir Portale, Automatisierungen oder Schnittstellen passend zum Prozess." }], links: ["dortmund", "herne", "witten", "essen"]
  },
  {
    slug: "witten", name: "Witten", eyebrow: "Webdesign für Witten", title: "Webdesign Witten: individuelle Websites & SEO", description: "Webdesign und Webentwicklung für Unternehmen in Witten. Schnelle Websites, lokale Sichtbarkeit und verständliche Kundenwege.", headline: "Digitale Klarheit für Unternehmen in Witten.",
    intro: "Wittener Unternehmen arbeiten häufig persönlich, spezialisiert und über Stadtgrenzen hinweg. Ihre Website sollte genau das abbilden: nahbar im Kontakt, präzise in der Leistung und professionell für Anfragen aus dem gesamten Ruhrgebiet.",
    contextTitle: "Persönliche Stärke digital nachvollziehbar machen", context: "Empfehlungen bleiben wichtig. Doch bevor jemand anruft, wird geprüft, verglichen und nach konkreten Antworten gesucht. Wir bauen Websites, die diese Vorprüfung bestehen: mit einer sauberen Informationsarchitektur, lokalen Bezügen und schnellen Kontaktmöglichkeiten – ohne die Marke auf austauschbare Regionalfloskeln zu reduzieren.",
    focus: ["Webdesign für Dienstleistung und Handwerk", "Inhalte für lokale und regionale Reichweite", "Klare Angebots- und Kontaktseiten", "Technische Modernisierung"],
    approachTitle: "Überschaubar im Prozess, stark im Ergebnis", approach: [{ title: "Ein fester roter Faden", text: "Jede Seite führt von einer konkreten Frage zu einer belastbaren Antwort und einem passenden nächsten Schritt." }, { title: "Schnell und zugänglich", text: "Schlanker Code, semantisches HTML und mobile Optimierung schaffen eine zuverlässige Basis." }, { title: "Ausbaufähig", text: "Die technische Struktur lässt sich später um weitere Leistungen, Standorte oder digitale Funktionen erweitern." }], links: ["bochum", "dortmund", "essen", "nrw"]
  },
  {
    slug: "recklinghausen", name: "Recklinghausen", eyebrow: "Webdesign für Recklinghausen", title: "Webdesign Recklinghausen & lokale SEO", description: "Websites und SEO für Unternehmen in Recklinghausen: hochwertiges Design, verständliche Inhalte und technische Qualität für mehr Anfragen.", headline: "Regional verankert. Digital konkurrenzfähig.",
    intro: "Recklinghausen ist Kreisstadt, Einkaufsstandort und Ausgangspunkt für ein großes regionales Einzugsgebiet. Eine gute Website kann diese Reichweite nutzen, wenn sie lokale Orientierung mit einer klaren Unternehmensposition verbindet.",
    contextTitle: "Mehr als nur für den eigenen Stadtteil sichtbar", context: "Kundschaft sucht in Recklinghausen, im Kreis und im nördlichen Ruhrgebiet. Wir entwickeln eine Seitenstruktur, die diese Ebenen sinnvoll abdeckt, ohne identische Ortsseiten zu vervielfältigen. Jede relevante Seite erhält einen eigenen Zweck, konkrete Informationen und passende interne Verbindungen.",
    focus: ["Lokale SEO für Stadt und Kreis", "Websites für Beratung und Fachbetriebe", "GEO-fähige Leistungsdarstellung", "Landingpages mit regionalem Fokus"],
    approachTitle: "Lokale Relevanz ohne künstliche Wiederholung", approach: [{ title: "Eigenständige Standortinhalte", text: "Jeder Ortsbezug folgt einer eigenen Suchintention und beantwortet regionale Fragen konkret." }, { title: "Vertrauen strukturiert aufbauen", text: "Leistungsumfang, Ablauf und häufige Fragen werden sichtbar, bevor Unsicherheit entsteht." }, { title: "Technisch sauber indexierbar", text: "Meta-Daten, Canonicals, Sitemap und strukturierte Daten werden von Anfang an mitgedacht." }], links: ["castrop-rauxel", "herne", "essen", "nrw"]
  },
  {
    slug: "essen", name: "Essen", eyebrow: "Webdesign für Essen", title: "Webdesign Essen: B2B, SEO & digitale Systeme", description: "Strategisches Webdesign, SEO, GEO und individuelle Software für Unternehmen in Essen. Klar positioniert und technisch leistungsfähig.", headline: "Ein digitaler Auftritt auf Augenhöhe mit Essens Wirtschaft.",
    intro: "Essen ist Konzernstandort, Dienstleistungszentrum und Heimat vieler spezialisierter Unternehmen. Wer hier digital überzeugen will, braucht mehr als eine gefällige Visitenkarte: Positionierung, Inhalte und Technik müssen zusammenarbeiten.",
    contextTitle: "Für komplexe Angebote und anspruchsvolle Entscheidungen", context: "Gerade im B2B-Umfeld sind Leistungen selten selbsterklärend. Wir strukturieren Fachwissen so, dass verschiedene Entscheider schnell die für sie relevante Information finden. Suchmaschinen erhalten klare Themenzusammenhänge, KI-Systeme zitierfähige Antworten und Interessenten einen nachvollziehbaren Weg zum Gespräch.",
    focus: ["B2B-Websites für erklärungsbedürftige Leistungen", "SEO-, GEO- und AEO-Architektur", "Conversion-Landingpages für Google Ads", "Portale, Tools und Prozessautomatisierung"],
    approachTitle: "Substanz für längere Entscheidungswege", approach: [{ title: "Mehrere Zielgruppen führen", text: "Geschäftsführung, Einkauf und Fachabteilungen erhalten unterschiedliche Einstiege in dieselbe klare Markenwelt." }, { title: "Expertise belegbar machen", text: "Leistungen, Vorgehen und Antworten werden konkret – damit Kompetenz nicht nur als Behauptung im Raum steht." }, { title: "Wachstum technisch vorbereiten", text: "Tracking, Kampagnen-Landingpages und Erweiterungen lassen sich auf einer sauberen Basis ergänzen." }], links: ["bochum", "recklinghausen", "dortmund", "nrw"]
  },
  {
    slug: "nrw", name: "Nordrhein-Westfalen", eyebrow: "Webdesign in NRW", title: "Webdesign NRW: Websites, SEO & Software", description: "Webdesign und digitale Systeme für Unternehmen in Nordrhein-Westfalen. Remote, strukturiert und individuell umgesetzt.", headline: "Digitale Systeme für Unternehmen in ganz NRW.",
    intro: "Nordrhein-Westfalen vereint dichte Ballungsräume, starke Industrieregionen und einen vielfältigen Mittelstand. Digitale Lösungen müssen deshalb lokale Märkte verstehen und zugleich überregional skalieren können.",
    contextTitle: "Regional ansprechbar, digital ohne Grenzen", context: "Die Zusammenarbeit funktioniert remote in klaren Etappen – von Analyse und Konzept über Design und Entwicklung bis zur Übergabe. Für Unternehmen mit mehreren Standorten planen wir eine SEO-Struktur, in der Regionen und Leistungen sinnvoll zusammenspielen, statt mit kopierten Stadtseiten um dieselben Suchbegriffe zu konkurrieren.",
    focus: ["Mehrstandort-Websites und regionale Architektur", "B2B-Sichtbarkeit in NRW", "Digitale Kunden- und Mitarbeiterprozesse", "Skalierbare Landingpage-Systeme"],
    approachTitle: "Ein System statt einzelner Insellösungen", approach: [{ title: "Standorte sinnvoll ordnen", text: "Regionale Seiten erhalten eine klare Rolle, eigene Inhalte und Verbindungen zu den passenden Leistungen." }, { title: "Remote transparent arbeiten", text: "Zwischenstände, Entscheidungen und nächste Schritte bleiben jederzeit nachvollziehbar." }, { title: "Von Website bis Software", text: "Wenn der Bedarf wächst, können Portale, Datenbanken und Automatisierungen direkt anknüpfen." }], links: ["dortmund", "bochum", "essen", "recklinghausen"]
  },
  {
    slug: "berlin", name: "Berlin", eyebrow: "Webdesign für Berlin", title: "Webdesign Berlin: klare Marken, starke Systeme", description: "Individuelles Webdesign, CRO, SEO und Software für Berliner Unternehmen. Remote entwickelt, technisch präzise und frei von Agentur-Templates.", headline: "In Berlins digitalem Lärm klar erkennbar bleiben.",
    intro: "Berlin ist schnell, international und voller digitaler Angebote. Aufmerksamkeit allein reicht hier nicht. Eine Website muss in wenigen Sekunden zeigen, was ein Unternehmen anders macht – und diese Position mit einer belastbaren Nutzererfahrung bestätigen.",
    contextTitle: "Eigenständigkeit statt des nächsten Startup-Looks", context: "Viele Berliner Websites ähneln sich: austauschbare Claims, vertraute SaaS-Karten und wenig greifbare Substanz. Wir entwickeln stattdessen eine visuelle und inhaltliche Logik aus dem tatsächlichen Angebot. Das Ergebnis wirkt charakteristisch, bleibt performant und führt trotz gestalterischer Eigenständigkeit klar zur Conversion.",
    focus: ["Markante Unternehmens- und Produktseiten", "CRO für digitale Angebote", "SEO und GEO für umkämpfte Themen", "Individuelle Webapps und MVP-Systeme"],
    approachTitle: "Schnelle Märkte brauchen eine klare Basis", approach: [{ title: "Positionierung sichtbar machen", text: "Typografie, Struktur und Tonalität entstehen aus dem Angebot – nicht aus einem Trend-Template." }, { title: "Tempo ohne technische Schulden", text: "Ein klarer Scope und moderne Entwicklung ermöglichen schnellen Fortschritt, ohne die Basis zu verbauen." }, { title: "Remote auf den Punkt", text: "Kurze Abstimmungen, dokumentierte Entscheidungen und sichtbare Zwischenstände halten das Projekt beweglich." }], links: ["nrw", "essen", "dortmund", "bochum"]
  }
];

export const locationMap = Object.fromEntries(locations.map(location => [location.slug, location]));
