export type ServicePageData = {
  slug: string; name: string; menuText: string; title: string; description: string; eyebrow: string; headline: string; intro: string; signal: string;
};

export const servicePages: ServicePageData[] = [
  { slug: "webdesign", name: "Webdesign", menuText: "Individuelle Websites statt Templates", title: "Webdesign: individuell, klar und conversionstark", description: "Individuelles Webdesign für Unternehmen: markengerecht, responsiv und konsequent auf Nutzerführung und Anfragen ausgerichtet.", eyebrow: "Individuelles Webdesign", headline: "Gestaltung, die nicht nach Vorlage aussieht.", intro: "Wir entwickeln eine visuelle Sprache aus Ihrem Unternehmen, Ihrem Angebot und den Entscheidungen Ihrer Kundschaft – statt eine bekannte Agenturvorlage neu einzufärben.", signal: "Eigenständig gestaltet. Klar geführt. Auf jedem Bildschirm präzise." },
  { slug: "webentwicklung", name: "Webentwicklung", menuText: "Sauberer Code für schnelle Websites", title: "Webentwicklung für schnelle und stabile Websites", description: "Moderne Webentwicklung mit Next.js und TypeScript: performant, wartbar, responsiv und technisch sauber umgesetzt.", eyebrow: "Moderne Webentwicklung", headline: "Sauber entwickelt. Schnell ausgeliefert.", intro: "Aus Konzept und Design wird eine robuste Website mit klarer Komponentenstruktur, kurzen Ladezeiten und einer technischen Basis, die sich sinnvoll erweitern lässt.", signal: "Performance, Wartbarkeit und Zugänglichkeit von Anfang an." },
  { slug: "website-optimierung", name: "Website-Optimierung", menuText: "Bestehendes gezielt besser machen", title: "Website-Optimierung für mehr Wirkung", description: "Bestehende Websites gezielt verbessern: Technik, Nutzerführung, Inhalte, Performance und Conversion ohne unnötigen Komplettumbau.", eyebrow: "Bestehendes verbessern", headline: "Was funktioniert, bleibt. Was bremst, wird besser.", intro: "Wir analysieren Ihre bestehende Website und optimieren gezielt die Stellen, an denen Sichtbarkeit, Bedienung, Geschwindigkeit oder Anfragen verloren gehen.", signal: "Gezielte Eingriffe statt reflexartigem Neubau." },
  { slug: "seo", name: "SEO", menuText: "Technische und inhaltliche Sichtbarkeit", title: "SEO: technische und inhaltliche Sichtbarkeit", description: "Suchmaschinenoptimierung mit technischer Basis, klarer Seitenarchitektur und hilfreichen Inhalten für relevante Suchanfragen.", eyebrow: "Search Engine Optimization", headline: "Gefunden werden, wenn Bedarf entsteht.", intro: "Wir verbinden technische Suchmaschinenoptimierung mit einer Seiten- und Inhaltsstruktur, die konkrete Suchintentionen beantwortet und langfristig ausgebaut werden kann.", signal: "Relevante Themen. Saubere Technik. Nachvollziehbare Struktur." },
  { slug: "geo", name: "GEO", menuText: "Optimierung für KI-Suchsysteme", title: "GEO für Sichtbarkeit in KI-Suchsystemen", description: "Generative Engine Optimization: Inhalte und Strukturen, die für KI-Suchsysteme verständlich, belastbar und zitierfähig sind.", eyebrow: "Generative Engine Optimization", headline: "Antworten schaffen, die KI-Systeme verstehen.", intro: "GEO macht Leistungen, Fachwissen und Aussagen maschinenlesbar und zitierfähig – mit präzisen Antworten, klaren Entitäten und belastbaren strukturierten Daten.", signal: "Klar formuliert. Strukturiert ausgezeichnet. Leicht zitierbar." },
  { slug: "aeo", name: "AEO", menuText: "Klare Antworten auf konkrete Fragen", title: "AEO: Antworten für moderne Sucherlebnisse", description: "Answer Engine Optimization für konkrete Kundenfragen, Featured Snippets und direkte Antworten in klassischen und KI-gestützten Suchen.", eyebrow: "Answer Engine Optimization", headline: "Die beste Antwort gewinnt Aufmerksamkeit.", intro: "Wir strukturieren Inhalte so, dass häufige und kaufentscheidende Fragen direkt, präzise und im richtigen Kontext beantwortet werden.", signal: "Fragen erkennen. Präzise antworten. Vertrauen aufbauen." },
  { slug: "cro", name: "CRO", menuText: "Mehr Anfragen aus bestehendem Traffic", title: "CRO: mehr qualifizierte Anfragen", description: "Conversion-Optimierung für Websites und Landingpages: klare Nutzerwege, weniger Reibung und bessere Kontaktquoten.", eyebrow: "Conversion Rate Optimization", headline: "Mehr Wirkung aus vorhandener Aufmerksamkeit.", intro: "Wir prüfen Einstiege, Argumentation, Nutzerwege und Kontaktpunkte – und beseitigen die Reibung, die zwischen Interesse und Anfrage entsteht.", signal: "Verstehen, priorisieren und nachvollziehbar optimieren." },
  { slug: "google-ads", name: "Google Ads", menuText: "Kampagnen mit passenden Landingpages", title: "Google Ads und leistungsfähige Landingpages", description: "Google-Ads-Kampagnen, Landingpages und Conversion-Struktur als abgestimmtes System für qualifizierte Anfragen.", eyebrow: "Bezahlte Sichtbarkeit", headline: "Anzeige und Zielseite müssen zusammenspielen.", intro: "Wir verbinden Kampagnenstruktur, Suchintention, Landingpage und Tracking-Vorbereitung, damit bezahlte Reichweite nicht an einer unklaren Zielseite verpufft.", signal: "Passende Botschaft vom Suchbegriff bis zur Anfrage." },
  { slug: "kundenmagnete", name: "Kundenmagnete", menuText: "Nützliche Einstiege in Ihren Funnel", title: "Kundenmagnete und Conversion-Funnel", description: "Kundenmagnete und Funnel, die echten Nutzen bieten und aus anonymem Interesse qualifizierte Kontakte machen.", eyebrow: "Leadgenerierung mit Nutzen", headline: "Ein guter Einstieg gibt zuerst etwas Wertvolles.", intro: "Wir konzipieren Rechner, Checks, Vorlagen, Guides oder andere nützliche Einstiege und verbinden sie mit einem nachvollziehbaren Weg zum nächsten Kontakt.", signal: "Nützlich für Interessenten. Relevant für den Vertrieb." },
  { slug: "automatisierung", name: "Automatisierung", menuText: "Wiederkehrende Abläufe vereinfachen", title: "Automatisierung für digitale Geschäftsprozesse", description: "Digitale Automatisierungen für wiederkehrende Abläufe, strukturierte Übergaben und weniger manuelle Routinearbeit.", eyebrow: "Weniger manuelle Routine", headline: "Abläufe vereinfachen, ohne Kontrolle abzugeben.", intro: "Wir identifizieren wiederkehrende Arbeitsschritte und entwickeln passende Automatisierungen – nachvollziehbar, wartbar und eingebettet in Ihren tatsächlichen Prozess.", signal: "Weniger Übertragungsfehler. Mehr Zeit für wichtige Entscheidungen." },
  { slug: "individuelle-software", name: "Individuelle Software", menuText: "Tools, Portale und interne Systeme", title: "Individuelle Software für konkrete Prozesse", description: "Individuelle Webapps, Kundenportale, interne Tools, Datenbanken und APIs, passend zu Ihren tatsächlichen Abläufen.", eyebrow: "Wenn Standard nicht passt", headline: "Software, die Ihrem Prozess folgt.", intro: "Wir entwickeln Webapps, Portale und interne Werkzeuge für konkrete Anforderungen – ohne Funktionen aufzublähen, die im Alltag niemand braucht.", signal: "Passend zum Ablauf. Erweiterbar. Verständlich dokumentiert." },
];

export const servicePageMap = Object.fromEntries(servicePages.map(service => [service.slug, service]));
