import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Datenschutzerklärung", description: "Informationen zur Verarbeitung personenbezogener Daten bei Digital Service Gross.", alternates: { canonical: "/datenschutz" } };
const env = process.env;
const value = (name: string | undefined, fallback: string) => name || fallback;

export default function Datenschutz() {
  return <LegalPage title="Datenschutzerklärung" updated="Oktober 2026">
    <h2>1. Verantwortlicher</h2><p>{value(env.LEGAL_NAME, "Digital Service Gross")}<br />{value(env.LEGAL_OWNER, "Verantwortliche Person bitte über LEGAL_OWNER hinterlegen")}<br />{value(env.LEGAL_STREET, "Anschrift bitte über LEGAL_STREET hinterlegen")}<br />{value(env.LEGAL_CITY, "Ort bitte über LEGAL_CITY hinterlegen")}<br />E-Mail: <a href="mailto:kontakt@digitalservicegross.de">kontakt@digitalservicegross.de</a></p>
    <h2>2. Hosting und Server-Logfiles</h2><p>Beim Aufruf dieser Website verarbeitet der Hostinganbieter technisch erforderliche Verbindungsdaten, insbesondere IP-Adresse, Datum und Uhrzeit, angeforderte Ressource, Referrer, Browsertyp und Betriebssystem. Die Verarbeitung erfolgt zur sicheren und stabilen Bereitstellung der Website auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Logdaten werden nur so lange gespeichert, wie dies für Betrieb und Sicherheit erforderlich ist.</p>
    <h2>3. Kontaktformular</h2><p>Wenn Sie das Kontaktformular nutzen, verarbeiten wir Ihren Namen, das Unternehmen, Ihre E-Mail-Adresse, eine freiwillig angegebene Telefonnummer, gewünschte Leistung, Budget und Projektbeschreibung. Die Übermittlung erfolgt serverseitig über eine verschlüsselte SMTP-Verbindung an das konfigurierte Postfach.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit Ihre Anfrage auf einen Vertrag oder vorvertragliche Maßnahmen gerichtet ist. Im Übrigen erfolgt die Verarbeitung auf Grundlage unseres berechtigten Interesses an der Bearbeitung geschäftlicher Anfragen gemäß Art. 6 Abs. 1 lit. f DSGVO. Die Angaben werden gelöscht, sobald die Anfrage abschließend bearbeitet ist und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p>
    <h2>4. Schutz vor Missbrauch</h2><p>Das Formular nutzt ein unsichtbares Honeypot-Feld und eine serverseitige Begrenzung wiederholter Anfragen. Dabei findet keine Übermittlung an externe Captcha- oder Analysedienste statt.</p>
    <h2>5. Cookies und Tracking</h2><p>Diese Website setzt in ihrer Grundkonfiguration keine Analyse-, Marketing- oder Drittanbieter-Cookies ein. Werden später optionale Trackingdienste ergänzt, wird diese Erklärung vor deren Aktivierung angepasst und – sofern erforderlich – eine Einwilligung eingeholt.</p>
    <h2>6. Empfänger und Drittlandtransfer</h2><p>Personenbezogene Daten erhalten nur Stellen, die sie für die genannten Zwecke benötigen, insbesondere der Hostinganbieter und der konfigurierte E-Mail-Anbieter. Eine Übermittlung in Drittländer ist nicht vorgesehen, sofern die eingesetzte Hosting- oder E-Mail-Infrastruktur nicht abweichend konfiguriert wird.</p>
    <h2>7. Ihre Rechte</h2><p>Sie haben nach Maßgabe der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Außerdem können Sie einer Verarbeitung aufgrund berechtigter Interessen widersprechen. Erteilte Einwilligungen können jederzeit mit Wirkung für die Zukunft widerrufen werden.</p><p>Sie haben zudem das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig ist grundsätzlich die Aufsichtsbehörde Ihres Wohnorts oder des Sitzes des Verantwortlichen.</p>
    <h2>8. Sicherheit und Aktualisierung</h2><p>Wir setzen angemessene technische und organisatorische Maßnahmen ein, um Daten gegen Verlust, Manipulation und unbefugten Zugriff zu schützen. Diese Erklärung wird angepasst, wenn sich Funktionen, Rechtslage oder eingesetzte Infrastruktur ändern.</p>
  </LegalPage>;
}
